services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_DATABASE: flask_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network

  backend:
    build: ./backend/
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    ports:
      - "3000:6000"
    environment:
      FLASK_ENV: development
      MONGO_URI: mongodb://root:root_password@mongodb:27017/flask_db?authSource=admin
    networks:
      - mongo_network

  web_app:
    build: ./web_app/
    restart: always
    depends_on:
      - backend
    volumes:
      - ./web_app:/app
    ports:
      - "80:6000"
    environment:
      FLASK_ENV: development
    networks:
      - mongo_network

  # mongo-express:
  #   image: mongo-express:latest
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root 
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: root_password
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #   ports:
  #     - "8080:8081"
  #   networks:
  #     - mongo_network

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web_app
    networks:
      - mongo_network

volumes:
  mongo_data:

networks:
  mongo_network:
    driver: bridge
